package CP::HelpTab;

use CP::Global qw/:FUNC :XPM/;
use CP::Help;

sub help {
  my($win) = shift;

  if ($win eq '') {
    makeImage("checkbox", \%XPM);
    $win = CP::Help->new("Chordy Help");
    $win->add(
[
 "<O TO:H:Tab Editor>",
 "\nMy first pass at writing a Tab editor.\nAt some point I'll get round to writing the help section in full :)\n\nThe editor is split vertically with the the left panel holding a series of buttons to manage Tab files, a centre panel to display what the final PDF page will look like (more or less) and a right panel to handle editing and Tab options. The PDF page is not editable directly (except for lyrics) but individual bars can be selected for editing at which point an edit window will pop into existance.\n",

 "<O To:H:Table Of Contents>",
 "<V 10>",
 "<O ES:S:Menu Section>",
 "<X open> <O OP:B:Open><V1>",
 "<X new> <O NW:B:New>",
 "<V 5>",
 "<X close> <O CS:B:Close><V1>",
 "<X delete> <O DE:B:Delete><V1>",
 "<V 10>",
 "<X save> <O SV:B:Save><V1>",
 "<X saveAs> <O SA:B:Save As><V1>",
 "<V 5>",
 "<O RT:P:  Rename Tab ><V1>",
 "<O XT:P:  Export Tab ><V1>",
 "<V 10>",
 "<X viewPDF> <O VP:B:View PDF><V1>",
 "<X makePDF> <O MP:B:Make PDF><V1>",
 "<X printPDF> <O PP:B:Print PDF><V1>",
 "<X batchPDF> <O BP:B:Batch Make PDFs><V1>",
 "<X saveclose> <O SM:B:Save, Make and Close PDF><V1>",
 "<X saveText> <O TS:B:Save As Text><V1>",
 "<V 10>",
 "<X exit> <O EX:B:Exit><V1>",
 "<X viewlog> <O VL:B:View Error Log><V1>",
 "<X clearlog> <O CL:B:Clear Error Log><V1>",
 "<X Find> <O VR:B:View Release Notes><V1>",
 "<X delete> <O DT:B:Delete Backup Tabs><V1>",
 "<V 10>",
 "<O CO:S:Collection><V5>",
 "<O ME:S:Media><V5>",
 "<O FO:S:Fonts><V5>",
 "<V 5>",
 "<O AB:P: About ><V1>",
 "<O HE:P: Help ><V1>",
 "<V 10>",

 "<O PD:S:PDF Page Display>",
 "<V 5>",
 "<O PB:S:Page Buttons>",
 "<V 5>",
 "<O EB:P: Edit Bar ><V1>",
 "<O CN:P: Clone Bar(s) ><V1>",
 "<V 10>",
 "<O CB:P: Copy Bar(s) ><V1>",
 "<O PO:P: Paste Over ><V1>",
 "<O PB:P: Paste Before ><V1>",
 "<O PA:P: Paste After ><V1>",
 "<V 10>",
 "<O SC:P: Clear Selection ><V1>",
 "<O BC:P: Clear Bar(s) ><V1>",
 "<O DB:P: Delete Bar(s) ><V1>",
 "<V 10>",
 "<O BS:P: Set Background ><V1>",
 "<O BC:P: Clear Background ><V1>",
 "<V 10>",
 "<O LY:S:Lyrics> ",
 "<V 5>",
 "<O PO:S:Page Options>",
 "<V 5>",
 "<O TR:S:Transpose>",
 "<V 5>",
 "<O CE:S:Colour Editor>",
 "<V 5>",
]);
    if (OS eq "win32") {
      $win->add(
[
 "<O TP:S:\nTab Player> ",
]);
    }
    $win->add(
[
 "<O ES:S:Edit Window>",
 "<V 5>",
 "<O EB:S:Edit Buttons>",
 "<V 5>",
 "<O FN:S:Fret Number/Rest>",
 "<V 5>",
 "<O SH:S:Slide - Hammer>",
 "<V 5>",
 "<O BR:S:Bend - Bend/Release>",
 "<V 5>",
 "<O BO:S:Bar Options>",
 "<V 10>",
 "<V 1#000000>",
 "<V 1>",
 "<V 1#000000>",
 "<V 10>",
 "<T ES><H Menu Section\n>",
 "<V10>",
 "<T OP><X open> <s Open> ",
 "<M>Allows you to select a Tab file from the current Collection.",
 "<V5>",
 "<T NW><X new> <s New> ",
 "<M>Prompts for a file name and creates a new Tab file.",
 "<V5>",
 "<T CS><X close> <s Close> ",
 "<M>Closes the current Tab session and prompts for a Save if any changes have been made.",
 "<V5>",
 "<T DE><X delete> <s Delete> ",
 "<M>Deletes the current Tab.\n",

 "<T SV><X save> <s Save> ",
 "<M>Saves the current Tab put keeps the edit session open.",
 "<V5>",
 "<T SA><X saveAs> <s Save As> ",
 "<M>Prompts for a new Tab name and Saves the current session to it and then opens the new Tab for editing.",
 "<V5>",
 "<T RT><P  Rename Tab > ",
 "<M>Renames the current Tab and continues the edit session.",
 "<V5>",
 "<T XT><P  Export Tab > ",
 "<M>Allows you to save the current session (with the current name) to a selectable folder.\n",

 "<T VP><X viewPDF> <s View PDF> ",
 "<M>Creates a temporary PDF and displays it in the viewer.",
 "<V5>",
 "<T MP><X makePDF> <s Make PDF> ",
 "<M>Make a permanent PDF in the PDF folder.",
 "<V5>",
 "<T PP><X printPDF> <s Print PDF> ",
 "<M>Creates a temporary PDF and Prints it.",
 "<V5>",
 "<T BP><X batchPDF> <s Batch Make PDFs> ",
 "<M>Lets you make a list of Tab files which are then sequentially processed by Make PDF.",
 "<V5>",
 "<T SM><X saveclose> <s Save, Make and Close PDF> ",
 "<M>Shortcut to perform each of the functions on the current Tab file.",
 "<V5>",
 "<T TS><X saveText> <s Save As Text> ",
 "<M>Creates a text file which is a close approximation to the PDF file.\n",

 "<T EX><X exit> <s Exit> ",
 "<M>Quits Tab but prompts to Save any changes if any have been made.\n",

 "<T VL><X viewlog> <s View Error Log> ",
 "<M>Displays the Error Log in a text window.",
 "<V5>",
 "<T CL><X clearlog> <s Clear Error Log> ",
 "<M>Removes everything from the current Error Log.",
 "<V5>",
 "<T VR><X Find> <s View Release Notes> ",
 "<M>Displays the Release Notes file in a text window.",
 "<V5>",
 "<T DT><X delete> <s Delete Backup Tabs> ",
 "<M>Every time a Teb file is modified and Saved the original is saved to a file in the Temp folder with an incrementing number as an extension. This function clears them out of the Temp folder.\n",

 "<T CO><P  Collection > ",
 "<M>Lets you Select/Edit the current Collection.",
 "<V5>",
 "<T ME><P  Media > ",
 "<M>Lets you Select/Edit the current Media type.",
 "<V5>",
 "<T FO><P  Fonts > ",
 "<M>Lets you change the different fonts and their colours/sizes/weights.\n",

 "<T AB><P  About > ",
 "<M>Shows the current Version number.",
 "<V5>",
 "<T HE><P  Help > ",
 "<M>That's how you got here!\n",

 "<T PD><H PDF Page Display\n>",
 "<V10>",
 "  This area shows a representation of what the final PDF will look like. This also has the number of the left most bar down the left side of the page display. You can select one or more Bars to be operated on by clicking the appropriate Bar(s) on the page. If you want to select a range of Bars, left-click on the first one and then shift-left-click on the second.",
 "<V10>",
 "<T PB><H Page Buttons\n>",
 "<V10>",
 "<P  Edit Bar > ",
 "<M>Click this after selecting a bar to transfer it to the Edit Section.",
 "<V5>",
 "<P  Clone Bar(s) > ",
 "<M>After selecting one or more bars this will copy the selection to the end of the current bars.",
 "<V5>",
 "<P  Copy Bar(s) > ",
 "<M>Copies the selected bar(s) to an internal buffer.\n",

 "<P  Paste Over > ",
 "<M>Any previously copied bars wil be pasted over the bars starting at the currently seleted bar.",
 "<V5>",
 "<P  Paste Before > ",
 "<M>As above but inserts the copied bars before the currently selected bar.",
 "<V5>",
 "<P  Paste After > ",
 "<M>As above but inserts the copied bars after the currently selected bar.\n",

 "<P  Clear Selection > ",
 "<M>If you've select one or more bars, This clears the selection.",
 "<V5>",
 "<P  Clear Bar(s) > ",
 "<M>Any selected bar(s) will be cleared of all Fret Numbers, Headings, etc.",
 "<V5>",
 "<P  Delete Bar(s) > ",
 "<M>Any selected bar(s) will be deleted and the trailing bars moved to fill the space vacated.\n",

 "<P  Set/Clear Background > ",
 "<M>Sets or Clears the background colour on one or more bars.\n",
 "<V5>",
 "<T LY><P  Lyrics > ",
 "<M>Moves all the Lyrics Up or Down one Stave. Any Lyrics that move up and off the first page will be placed after the last line of Lyrics.\n",

 "<P  {{{ Prev Page >  and  <P  }}} Next Page > ",
 "<M>Move backward or forward one page.\n",

 "<T PO><S Page Options>",
 "<V5>",
 "The PDF page <B Tab File Name, PDF File Name> and <B Title> are inter-related in that, by default, the <B PDF File Name> is taken from the <B Tab File Name> with a <s .pdf> extension or visa versa, depending on which comes first. The <B Title> is the same text but without an extension. The only immutable item is the <B Tab File Name>, both the other entries can be changed to your own preference. For instance, I use some software that displays a PDF on my tablet and links a song into its database via the file name. It's not unknown for the vocalist(s) to decide the key needs changing in which case I have a separate <B Tab File Name> which has the same <B PDF File Name> and <B Title> as the original - the database thinks the new file (with new key!) is still the original file and saves me having to manipulate the database or add a new song with a different title.",
 "If you want a short note to appear at the top of the PDF page (top right), edit the <B Heading Note> box.",
 "The <s Key> is initially taken to be the first note played but can be over-ridden with an entry in the <B Set Key as> box.",
 "<V5>",
 "<P  Intrument > ",
 "This button just shows the correct number of strings in each bar.",
 "<V5>",
 "<P  Timing > ",
 "Use this to change the number of crotchets per Bar - currently only 2/4, 3/4 and 4/4 are implemented.",
 "<V5>",
 "<P  Edit Scale > ",
 "This value makes the bar edit area bigger or smaller to make editing easier.",
 "<V5>",
 "<P  Bars/Stave > ",
 "Fairly obvious what this does!",
 "<V5>",
 "<P  String Spacing > ",
 "Simply increases/decreases the distance between string lines in a Bar in 1 point increments.",
 "<V5>",
 "<P  Inter-Stave Gap > ",
 "Enables you to add extra space between each Stave Lyric set.",
 "<V5>",
 "<P  Lyric Lines > ",
 "Sets the number of lyric lines below each Stave. They are shown as a background colour on the PDF page but that colour is <s NOT> transfered to the final PDF when generated.",
 "<R NOTE:> When there are 2 or more Lyric lines below each stave, these are <B individual> lines ie. you can't hit the <B Enter> key and expect to be on the next line down.",
 "Increasing the number of lines causes an extra (blank) line to be added to each stave. Decreasing the number of lines causes layout issues - the current policy is to have a stab at intelligently removing blank lines from each stave <B if> we can do it to <B ALL> staves otherwise we just distribute the existing lyrics into the new number of lines per stave. This will cause some wierd effects if for example you have one line of lyrics per stave and increase to two then decrease back to one after adding text to the second line of the first stave. You'll end up with every other lyric line blank.",
 "<V5>",
 "<P  Lyric Spacing > ",
 "Adds extra space between Lyric lines but only if more that one is defined.\n",

 "<T TR><S Transpose>",
 "<V5>",
 "The <B Semi-tones> box lets you move the fret numbers up and down the scale in semitone increments. Normaly, if you transpose down and the fret number goes negative, the number will be shown in <R RED>. If you have the <B Adjust Strings> box ticked the fret number will be moved down one string to the appropriate fret. The only exception is if you then run out of strings in which case the appropraite fret one octave higher will be shown.",
 "The <B One String> buttons move all the Fret numbers up or down one string. I put this in mainly for moving Tabs from a 4 string to a 5 string bass and vice versa.\n",

 "<T CE><H Colour Editor (Backgrounds and Fonts)\n>",
 "<V10>",

 "  In the colour editor you get 3 sliders that go from 0 to 255 for each primary colour where 0 is no colour and 255 is lots. The resulting mix is shown in a box on the right of the window. This box can have both the background and foreground colours changed but what will be used depends on what mode the editor is in (see the heading top right).",
 "Below the sliders is an entry area where you can modify the Hex values for a given colour. If a colour matches one of those listed on the left, that name will appear in this entry box.\n",
 "Below this are three buttons which give you quick access to the current Chorus, Highlight and Comment colours.",
 "The \"My Colours\" box gives you the ability to mix and save 16 different colours you might want to use on a regular basis. Clicking on one of the 16 buttons will set that fore/back-ground colour. If you then change the colour with the sliders, you can change the selected colour swatch with the <R Set Colour> button. These colours are only saved if you hit the <R OK> button.\n",
]);
    if (OS eq "win32") {
      $win->add(
[
 "<T TP><H Tab Player\n>",
 "<V10>",
 "Use the slider to set the tempo of the piece (beats/minute). If no start or stop bar is selected then the whole piece will be played. If just the start is selected then play will continue to the end of the piece. If both are selected then the (inclusive) bars will be played. The same applies to the 'Loop' function. If you 'Pause' play, you can continue with either the 'Play' or the 'Loop' button and play will continue in that mode.\n"
]);
    }
  }
  $win->add(
[
 "<T ES><H Bar Edit Window\n>",
 "<V 10>",
 "  This is where all the real work happens and shows two Bars - the one on the left can be edited, the one on the right is really just there so that you can easily see what is comong next. The horizontal lines represent instrument strings - the lowest note string is at the bottom. The vertical lines (not either end of the stave) are the major beats in each bar - crotchets. The subdivisions then represent quavers, semiquavers and demisemiquavers.\nFrets/Rests are selected and placed by clicking on one of the horizontal/vertical intersections. They can then be deleted by right clicking on them or selected for moving by left clicking on them. If a Fret/Rest is selected it will turn <R red> and can then be moved to a new position by left clicking on the new position.\n",

 "<T EB><S Edit Buttons>",
 "<V 10>",
 "These buttons affect what happens in or to the Edit Stave\n",
 "<P  }}} Cancel {{{ > ",
 "<M>Any items in the Edit area and any selections in the PDF page are removed.",
 "<V5>",
 "<P  Clear Bar > ",
 "<M>Clears any items in the Edit area.",
 "<V5>",
 "<P  Set Background > ",
 "<M>Allows you to define a background colour for this single Bar.",
 "<V5>",
 "<P  Clear Background > ",
 "<M>Clears any background colour from the Bar.",
 "<V5>",
 "<P  Insert Before > ",
 "<M>If you have selected a Bar from the PDF page, the current Bar will be saved and inserted <s before> the selected Bar.",
 "<V5>",
 "<P  Insert After > ",
 "<M>Same as above except the Bar will be inserted <s after> the selected Bar.",
 "<V5>",
 "<P  Update > ",
 "<M>Updates the Bar on the PDF page but remains in the Editor.",
 "<V5>",
 "<P  Save > ",
 "<M>If a PDF page Bar has been selected for editing it will be replaced otherwise the edited Bar will be tacked onto the end of any existing Bars.\n",

 "<T FN><S Fret Number/Rest>",
 "<V5>",
 "Clicking on any one will select it for insertion into the Edit Stave.\n",

 "<T SH><S Slide - Hammer>",
 "<V5>",
 "Where 2 Fret Numbers appear adjacent on <s ONE> string - click on the <R Slide> or <R Hammer> button and then click on the first (or left most) of the 2 Fret Numbers.\n",

 "<T BR><S Bend - Bend/Release>",
 "<V5>",
 "These 2 are slightly different. For just a Bend, click on the <R Bend> button and then click on the Fret Number you want bent. For Bend/Release click on the <R Bend/Release> button and then click on the Fret Number then click on the horizontal/vertical intersection where you want the Release to end.\n",

 "<T BO><S Bar Options>",
 "<V5>",
 "These are mainly to handle stuff other than Fret Numbers and Rests.\nPlace any text you want above the staff in the <B Header Text> box. This can be <B Left> or <B Right> justified and can have <B Volta brackets> included by selecting the appropriate button option.\nThe <B Repeat> options place a start or end Repeat sign into the Bar.\nThe <B Note Font> option lets you reduce the size of the font - useful where frets are played very close together and would otherwise overlap.\nThe <B Bar Starts New Line/Page> option does just that - it forces the Bar onto a new line or page.\n",

]);

  $win->show();
  $win;
}

1;
